//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class akademikEntities : DbContext
    {
        public akademikEntities()
            : base("name=akademikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dosen> dosen { get; set; }
        public virtual DbSet<mahasiswa> mahasiswa { get; set; }
        public virtual DbSet<matakuliah> matakuliah { get; set; }
        public virtual DbSet<ruang_kuliah> ruang_kuliah { get; set; }
    }
}
