//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahasiswa
    {
        public string id { get; set; }
        public string nama { get; set; }
        public string jenis_kelamin { get; set; }
        public string prodi { get; set; }
        public string alamat { get; set; }
        public string email { get; set; }
        public string telepon { get; set; }
        public string id_prodi { get; set; }
        public string id_dosen { get; set; }
    
        public virtual mahasiswa mahasiswa1 { get; set; }
        public virtual mahasiswa mahasiswa2 { get; set; }
    }
}
