//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruang_kuliah
    {
        public string id { get; set; }
        public string nama { get; set; }
        public Nullable<decimal> kuota { get; set; }
    }
}
